name: release

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build app
      run: yarn build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: published

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: published
      - name: Transfering files
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: published
          remote: /var/sites/devtranslate.io
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          atomicPut: true
